[package]
name = "bitcoin-rest-block-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9"
hex = "0.4"
num-format = "0.4"
tokio = { version = "1", features = ["full"] }
rayon = "1.10"
reqwest = "0.12"
bitcoin_hashes = "0.16"

